// Package hookgen generates app hook scaffolds and project runner wiring.
package hookgen

import (
	"bufio"
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/dygo-dev/dygo/internal/app/manifest"
	appregistry "github.com/dygo-dev/dygo/internal/app/registry"
	"github.com/dygo-dev/dygo/internal/entity/catalog"
	"github.com/dygo-dev/dygo/internal/entity/fieldtype"
	"github.com/dygo-dev/dygo/internal/project"
)

const generatedHeader = "// Code generated by dygo hooks generate; DO NOT EDIT."

// Result describes files touched by hook scaffold generation.
type Result struct {
	AppName string
	Entity  string

	HookFile     string
	RegisterFile string
	RunnerFile   string

	HookFileCreated     bool
	RegisterFileWritten bool
	RunnerFileWritten   bool
}

type hookApp struct {
	AppName    string
	HooksDir   string
	ImportPath string
	Alias      string
}

// RunnerUpdate describes a generated project runner update.
type RunnerUpdate struct {
	RunnerFile string
	Source     []byte
}

// Generate creates an Entity hook scaffold and updates generated runner wiring.
func Generate(root string, appName string, entityName string) (Result, error) {
	root = filepath.Clean(root)
	appName = strings.TrimSpace(appName)
	entityName = strings.TrimSpace(entityName)
	if appName == "" {
		return Result{}, fmt.Errorf("app name is required")
	}
	if entityName == "" {
		return Result{}, fmt.Errorf("entity name is required")
	}
	if err := requireGeneratedProjectRoot(root); err != nil {
		return Result{}, err
	}

	modulePath, err := readModulePath(root)
	if err != nil {
		return Result{}, err
	}
	apps, err := appregistry.New(root).Validate()
	if err != nil {
		return Result{}, fmt.Errorf("validate apps: %w", err)
	}
	entities, err := catalog.New(apps, fieldtype.DefaultRegistry()).Validate()
	if err != nil {
		return Result{}, fmt.Errorf("validate entities: %w", err)
	}

	app, ok := findApp(apps, appName)
	if !ok {
		return Result{}, fmt.Errorf("app %q not found", appName)
	}
	if !isProjectOwnedApp(root, app.Dir) {
		return Result{}, fmt.Errorf("app %q is not a project-owned app under apps/", appName)
	}
	if !hasEntity(entities, appName, entityName) {
		return Result{}, fmt.Errorf("entity %q not found in app %q", entityName, appName)
	}

	hooksDir := filepath.Join(app.Dir, filepath.FromSlash(app.Manifest.Paths.WithDefaults().Hooks))
	hookFile := filepath.Join(hooksDir, entityName+".go")
	registerFile := filepath.Join(hooksDir, "register.go")
	runnerFile := filepath.Join(root, "cmd", "dygo", "main.go")

	if err := preflightPath(hooksDir, wantDirectory); err != nil {
		return Result{}, err
	}
	if err := preflightPath(hookFile, wantRegularFile); err != nil {
		return Result{}, err
	}
	if err := preflightGeneratedFile(registerFile, registerManualSnippet(entityName)); err != nil {
		return Result{}, err
	}
	if err := preflightGeneratedFile(runnerFile, runnerManualSnippet(root, modulePath, appName, hooksDir)); err != nil {
		return Result{}, err
	}

	registerEntities, err := registerEntitiesForApp(hooksDir, appName, entityName, entities)
	if err != nil {
		return Result{}, err
	}
	hookApps, err := collectHookApps(root, modulePath, apps, appName)
	if err != nil {
		return Result{}, err
	}

	hookSource, err := renderEntityHookSource(appName, entityName)
	if err != nil {
		return Result{}, err
	}
	registerSource, err := renderRegisterSource(registerEntities)
	if err != nil {
		return Result{}, err
	}
	runnerSource, err := renderRunnerSource(hookApps)
	if err != nil {
		return Result{}, err
	}

	result := Result{
		AppName:      appName,
		Entity:       entityName,
		HookFile:     hookFile,
		RegisterFile: registerFile,
		RunnerFile:   runnerFile,
	}
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return Result{}, fmt.Errorf("create hooks directory %s: %w", hooksDir, err)
	}
	if _, err := os.Stat(hookFile); err != nil {
		if !os.IsNotExist(err) {
			return Result{}, fmt.Errorf("stat hook file %s: %w", hookFile, err)
		}
		if err := os.WriteFile(hookFile, hookSource, 0o644); err != nil {
			return Result{}, fmt.Errorf("write hook file %s: %w", hookFile, err)
		}
		result.HookFileCreated = true
	}
	written, err := writeFileIfChanged(registerFile, registerSource)
	if err != nil {
		return Result{}, err
	}
	result.RegisterFileWritten = written
	if err := os.MkdirAll(filepath.Dir(runnerFile), 0o755); err != nil {
		return Result{}, fmt.Errorf("create runner directory %s: %w", filepath.Dir(runnerFile), err)
	}
	written, err = writeFileIfChanged(runnerFile, runnerSource)
	if err != nil {
		return Result{}, err
	}
	result.RunnerFileWritten = written
	return result, nil
}

// RenderRunner renders the project runner for all app hooks that expose Register.
func RenderRunner(root string) (RunnerUpdate, error) {
	root = filepath.Clean(root)
	if err := requireGeneratedProjectRoot(root); err != nil {
		return RunnerUpdate{}, err
	}
	modulePath, err := readModulePath(root)
	if err != nil {
		return RunnerUpdate{}, err
	}
	apps, err := appregistry.New(root).Validate()
	if err != nil {
		return RunnerUpdate{}, fmt.Errorf("validate apps: %w", err)
	}

	runnerFile := filepath.Join(root, "cmd", "dygo", "main.go")
	if err := preflightGeneratedFile(runnerFile, runnerUpgradeManualSnippet()); err != nil {
		return RunnerUpdate{}, err
	}
	hookApps, err := collectHookApps(root, modulePath, apps, "")
	if err != nil {
		return RunnerUpdate{}, err
	}
	runnerSource, err := renderRunnerSource(hookApps)
	if err != nil {
		return RunnerUpdate{}, err
	}
	return RunnerUpdate{RunnerFile: runnerFile, Source: runnerSource}, nil
}

// UpdateRunner writes the generated project runner when its content changes.
func UpdateRunner(root string) (RunnerUpdate, bool, error) {
	update, err := RenderRunner(root)
	if err != nil {
		return RunnerUpdate{}, false, err
	}
	if err := os.MkdirAll(filepath.Dir(update.RunnerFile), 0o755); err != nil {
		return RunnerUpdate{}, false, fmt.Errorf("create runner directory %s: %w", filepath.Dir(update.RunnerFile), err)
	}
	written, err := writeFileIfChanged(update.RunnerFile, update.Source)
	if err != nil {
		return RunnerUpdate{}, false, err
	}
	return update, written, nil
}

func requireGeneratedProjectRoot(root string) error {
	marker := filepath.Join(root, project.MarkerFile)
	info, err := os.Stat(marker)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("hook generation requires a dygo project root with %s", project.MarkerFile)
		}
		return fmt.Errorf("stat dygo project marker %s: %w", marker, err)
	}
	if info.IsDir() {
		return fmt.Errorf("dygo project marker %s must be a file", marker)
	}
	return nil
}

func readModulePath(root string) (string, error) {
	path := filepath.Join(root, "go.mod")
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read go module %s: %w", path, err)
	}
	scanner := bufio.NewScanner(bytes.NewReader(data))
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) >= 2 && fields[0] == "module" {
			return fields[1], nil
		}
	}
	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("scan go module %s: %w", path, err)
	}
	return "", fmt.Errorf("go module %s is missing a module directive", path)
}

func findApp(apps []manifest.LoadedApp, appName string) (manifest.LoadedApp, bool) {
	for _, app := range apps {
		if app.Manifest.Name == appName {
			return app, true
		}
	}
	return manifest.LoadedApp{}, false
}

func isProjectOwnedApp(root string, appDir string) bool {
	relative, err := filepath.Rel(root, appDir)
	if err != nil {
		return false
	}
	parts := strings.Split(filepath.ToSlash(relative), "/")
	return len(parts) == 2 && parts[0] == "apps" && parts[1] != ""
}

func hasEntity(entities []catalog.LoadedEntity, appName string, entityName string) bool {
	for _, entity := range entities {
		if entity.AppName == appName && entity.Entity.Name == entityName {
			return true
		}
	}
	return false
}

type pathExpectation int

const (
	wantDirectory pathExpectation = iota
	wantRegularFile
)

func preflightPath(path string, want pathExpectation) error {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("stat %s: %w", path, err)
	}
	switch want {
	case wantDirectory:
		if !info.IsDir() {
			return fmt.Errorf("%s must be a directory", path)
		}
	case wantRegularFile:
		if info.IsDir() || !info.Mode().IsRegular() {
			return fmt.Errorf("%s must be a regular file", path)
		}
	}
	return nil
}

func preflightGeneratedFile(path string, manualSnippet string) error {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("stat %s: %w", path, err)
	}
	if info.IsDir() || !info.Mode().IsRegular() {
		return fmt.Errorf("%s must be a regular file", path)
	}
	generated, err := isGeneratedFile(path)
	if err != nil {
		return err
	}
	if !generated {
		return fmt.Errorf("%s exists and is not dygo-generated; add wiring manually:\n%s", path, strings.TrimSpace(manualSnippet))
	}
	return nil
}

func isGeneratedFile(path string) (bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return false, fmt.Errorf("read %s: %w", path, err)
	}
	source := string(data)
	if strings.Contains(source, generatedHeader) {
		return true, nil
	}
	return strings.Contains(source, "Code generated by dygo") && strings.Contains(source, "DO NOT EDIT."), nil
}

func registerEntitiesForApp(hooksDir string, appName string, entityName string, entities []catalog.LoadedEntity) ([]string, error) {
	knownEntities := map[string]struct{}{}
	for _, entity := range entities {
		if entity.AppName == appName {
			knownEntities[entity.Entity.Name] = struct{}{}
		}
	}

	names := map[string]struct{}{entityName: {}}
	entries, err := os.ReadDir(hooksDir)
	if err != nil {
		if os.IsNotExist(err) {
			return sortedKeys(names), nil
		}
		return nil, fmt.Errorf("read hooks directory %s: %w", hooksDir, err)
	}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".go" {
			continue
		}
		if entry.Name() == "register.go" || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		info, err := entry.Info()
		if err != nil {
			return nil, fmt.Errorf("stat hook file %s: %w", filepath.Join(hooksDir, entry.Name()), err)
		}
		if !info.Mode().IsRegular() {
			continue
		}
		name := strings.TrimSuffix(entry.Name(), filepath.Ext(entry.Name()))
		if _, ok := knownEntities[name]; ok {
			names[name] = struct{}{}
		}
	}
	return sortedKeys(names), nil
}

func collectHookApps(root string, modulePath string, apps []manifest.LoadedApp, targetAppName string) ([]hookApp, error) {
	var hookApps []hookApp
	for _, app := range apps {
		if !isProjectOwnedApp(root, app.Dir) {
			continue
		}
		hooksDir := filepath.Join(app.Dir, filepath.FromSlash(app.Manifest.Paths.WithDefaults().Hooks))
		include := app.Manifest.Name == targetAppName
		if !include {
			hasRegister, err := hooksPackageHasRegister(hooksDir)
			if err != nil {
				return nil, err
			}
			include = hasRegister
		}
		if !include {
			continue
		}
		importPath, err := importPathForDir(root, modulePath, hooksDir)
		if err != nil {
			return nil, err
		}
		hookApps = append(hookApps, hookApp{
			AppName:    app.Manifest.Name,
			HooksDir:   hooksDir,
			ImportPath: importPath,
		})
	}
	sort.SliceStable(hookApps, func(i, j int) bool {
		return hookApps[i].AppName < hookApps[j].AppName
	})
	assignImportAliases(hookApps)
	return hookApps, nil
}

func hooksPackageHasRegister(hooksDir string) (bool, error) {
	entries, err := os.ReadDir(hooksDir)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("read hooks directory %s: %w", hooksDir, err)
	}
	hasGoFile := false
	for _, entry := range entries {
		if !entry.IsDir() && filepath.Ext(entry.Name()) == ".go" && !strings.HasSuffix(entry.Name(), "_test.go") {
			hasGoFile = true
			break
		}
	}
	if !hasGoFile {
		return false, nil
	}

	fset := token.NewFileSet()
	packages, err := parser.ParseDir(fset, hooksDir, func(info fs.FileInfo) bool {
		return info.Mode().IsRegular() && filepath.Ext(info.Name()) == ".go" && !strings.HasSuffix(info.Name(), "_test.go")
	}, 0)
	if err != nil {
		return false, fmt.Errorf("parse hooks package %s: %w", hooksDir, err)
	}
	for _, pkg := range packages {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				fn, ok := decl.(*ast.FuncDecl)
				if ok && fn.Recv == nil && fn.Name.Name == "Register" {
					return true, nil
				}
			}
		}
	}
	return false, nil
}

func importPathForDir(root string, modulePath string, dir string) (string, error) {
	relative, err := filepath.Rel(root, dir)
	if err != nil {
		return "", fmt.Errorf("resolve hooks import path for %s: %w", dir, err)
	}
	if strings.HasPrefix(relative, "..") {
		return "", fmt.Errorf("hooks directory %s is outside project root", dir)
	}
	return strings.TrimRight(modulePath, "/") + "/" + filepath.ToSlash(relative), nil
}

func assignImportAliases(hookApps []hookApp) {
	used := map[string]int{}
	for index := range hookApps {
		base := lowerIdentifier(hookApps[index].AppName) + "hooks"
		if base == "hooks" {
			base = "apphooks"
		}
		count := used[base]
		used[base] = count + 1
		if count == 0 {
			hookApps[index].Alias = base
			continue
		}
		hookApps[index].Alias = fmt.Sprintf("%s%d", base, count+1)
	}
}

func renderEntityHookSource(appName string, entityName string) ([]byte, error) {
	name := exportedIdentifier(entityName)
	source := fmt.Sprintf(`package hooks

import (
	"context"

	"github.com/dygo-dev/dygo/pkg/sdk"
)

func register%[1]sHooks(registry sdk.RecordHookRegistry) error {
	if err := registry.RegisterEntity(%[2]q, %[3]q, sdk.RecordBeforeCreate, %[4]q, beforeCreate%[1]s); err != nil {
		return err
	}
	if err := registry.RegisterEntity(%[2]q, %[3]q, sdk.RecordAfterCreate, %[5]q, afterCreate%[1]s); err != nil {
		return err
	}
	if err := registry.RegisterEntity(%[2]q, %[3]q, sdk.RecordBeforeUpdate, %[6]q, beforeUpdate%[1]s); err != nil {
		return err
	}
	if err := registry.RegisterEntity(%[2]q, %[3]q, sdk.RecordAfterUpdate, %[7]q, afterUpdate%[1]s); err != nil {
		return err
	}
	return nil
}

func beforeCreate%[1]s(ctx context.Context, dygo sdk.RecordHook) error {
	return nil
}

func afterCreate%[1]s(ctx context.Context, dygo sdk.RecordHook) error {
	return nil
}

func beforeUpdate%[1]s(ctx context.Context, dygo sdk.RecordHook) error {
	return nil
}

func afterUpdate%[1]s(ctx context.Context, dygo sdk.RecordHook) error {
	return nil
}
`, name, appName, entityName, entityName+"-before-create", entityName+"-after-create", entityName+"-before-update", entityName+"-after-update")
	return formatGoSource([]byte(source))
}

func renderRegisterSource(entities []string) ([]byte, error) {
	var builder strings.Builder
	builder.WriteString(generatedHeader)
	builder.WriteString("\n\npackage hooks\n\n")
	builder.WriteString("import \"github.com/dygo-dev/dygo/pkg/sdk\"\n\n")
	builder.WriteString("func Register(registry sdk.RecordHookRegistry) error {\n")
	for _, entity := range entities {
		builder.WriteString(fmt.Sprintf("\tif err := register%sHooks(registry); err != nil {\n", exportedIdentifier(entity)))
		builder.WriteString("\t\treturn err\n")
		builder.WriteString("\t}\n")
	}
	builder.WriteString("\treturn nil\n")
	builder.WriteString("}\n")
	return formatGoSource([]byte(builder.String()))
}

func renderRunnerSource(hookApps []hookApp) ([]byte, error) {
	var builder strings.Builder
	builder.WriteString(generatedHeader)
	builder.WriteString("\n\npackage main\n\n")
	builder.WriteString("import (\n")
	builder.WriteString("\t\"context\"\n")
	builder.WriteString("\t\"fmt\"\n")
	builder.WriteString("\t\"os\"\n")
	builder.WriteString("\t\"os/signal\"\n")
	builder.WriteString("\t\"syscall\"\n\n")
	for _, app := range hookApps {
		builder.WriteString(fmt.Sprintf("\t%s %q\n", app.Alias, app.ImportPath))
	}
	builder.WriteString("\t\"github.com/dygo-dev/dygo/pkg/sdk\"\n")
	builder.WriteString("\tdygoruntime \"github.com/dygo-dev/dygo/pkg/sdk/runtime\"\n")
	builder.WriteString(")\n\n")
	builder.WriteString("func main() {\n")
	builder.WriteString("\tctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)\n")
	builder.WriteString("\tdefer stop()\n\n")
	builder.WriteString("\terr := dygoruntime.Run(ctx, os.Args[1:], os.Stdin, os.Stdout, os.Stderr, dygoruntime.Options{\n")
	builder.WriteString("\t\tRecordHooks: []sdk.RecordHookRegistrar{\n")
	for _, app := range hookApps {
		builder.WriteString(fmt.Sprintf("\t\t\t%s.Register,\n", app.Alias))
	}
	builder.WriteString("\t\t},\n")
	builder.WriteString("\t})\n")
	builder.WriteString("\tif err != nil {\n")
	builder.WriteString("\t\tfmt.Fprintln(os.Stderr, err)\n")
	builder.WriteString("\t\tos.Exit(1)\n")
	builder.WriteString("\t}\n")
	builder.WriteString("}\n")
	return formatGoSource([]byte(builder.String()))
}

func formatGoSource(source []byte) ([]byte, error) {
	formatted, err := format.Source(source)
	if err != nil {
		return nil, fmt.Errorf("format generated Go source: %w", err)
	}
	return formatted, nil
}

func writeFileIfChanged(path string, data []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, data) {
		return false, nil
	}
	if err != nil && !os.IsNotExist(err) {
		return false, fmt.Errorf("read %s: %w", path, err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return false, fmt.Errorf("write %s: %w", path, err)
	}
	return true, nil
}

func registerManualSnippet(entityName string) string {
	return fmt.Sprintf(`func Register(registry sdk.RecordHookRegistry) error {
	if err := register%sHooks(registry); err != nil {
		return err
	}
	return nil
}`, exportedIdentifier(entityName))
}

func runnerManualSnippet(root string, modulePath string, appName string, hooksDir string) string {
	alias := lowerIdentifier(appName) + "hooks"
	importPath, err := importPathForDir(root, modulePath, hooksDir)
	if err != nil {
		importPath = strings.TrimRight(modulePath, "/") + "/" + filepath.ToSlash(filepath.Clean(hooksDir))
	}
	if alias == "hooks" {
		alias = "apphooks"
	}
	return fmt.Sprintf(`import %s %q

RecordHooks: []sdk.RecordHookRegistrar{%s.Register},`, alias, importPath, alias)
}

func runnerUpgradeManualSnippet() string {
	return `cmd/dygo/main.go is custom. Import app hook packages manually and call pkg/sdk/runtime.Run with runtime.Options{RecordHooks: ...}.`
}

func exportedIdentifier(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	var builder strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		runes := []rune(part)
		builder.WriteRune(unicode.ToUpper(runes[0]))
		for _, r := range runes[1:] {
			builder.WriteRune(r)
		}
	}
	if builder.Len() == 0 {
		return "Entity"
	}
	return builder.String()
}

func lowerIdentifier(value string) string {
	var builder strings.Builder
	for _, r := range value {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			builder.WriteRune(unicode.ToLower(r))
		}
	}
	return builder.String()
}

func sortedKeys(values map[string]struct{}) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
