package hookgen

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hapyco/dygo/internal/runnergen"
)

func TestGenerateCreatesHookRegisterAndRunner(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales", "")
	writeTestEntity(t, root, "sales", "lead")

	result, err := Generate(root, "sales", "lead")
	if err != nil {
		t.Fatalf("Generate() error = %v, want nil", err)
	}
	if !result.HookFileCreated || !result.RunnerFileWritten {
		t.Fatalf("Generate() result = %+v, want created/written files", result)
	}

	hookSource := readTestFile(t, filepath.Join(root, "apps", "sales", "entities", "lead", "hooks.go"))
	if strings.Contains(hookSource, "DO NOT EDIT") || strings.Contains(hookSource, "Code generated by dygo") {
		t.Fatalf("hook source = %q, want developer-owned starter without generated ownership header", hookSource)
	}
	for _, want := range []string{
		"func Register(registry dygo.RecordHookRegistry) error",
		`dygo.RecordBeforeCreate, "lead-before-create", beforeCreateLead`,
		`dygo.RecordAfterCreate, "lead-after-create", afterCreateLead`,
		`dygo.RecordBeforeUpdate, "lead-before-update", beforeUpdateLead`,
		`dygo.RecordAfterUpdate, "lead-after-update", afterUpdateLead`,
		"func beforeCreateLead(ctx context.Context, hook dygo.RecordHook) error",
		"func afterCreateLead(ctx context.Context, hook dygo.RecordHook) error",
		"func beforeUpdateLead(ctx context.Context, hook dygo.RecordHook) error",
		"func afterUpdateLead(ctx context.Context, hook dygo.RecordHook) error",
	} {
		if !strings.Contains(hookSource, want) {
			t.Fatalf("hook source = %q, want substring %q", hookSource, want)
		}
	}

	runnerSource := readTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"))
	for _, want := range []string{
		runnergen.GeneratedHeader,
		`salesleadhooks "example.com/acme/apps/sales/entities/lead"`,
		"dygoruntime.Run(ctx, os.Args[1:], os.Stdin, os.Stdout, os.Stderr",
		"salesleadhooks.Register",
	} {
		if !strings.Contains(runnerSource, want) {
			t.Fatalf("runner source = %q, want substring %q", runnerSource, want)
		}
	}

	second, err := Generate(root, "sales", "lead")
	if err != nil {
		t.Fatalf("Generate() second error = %v, want nil", err)
	}
	if second.HookFileCreated || second.RunnerFileWritten {
		t.Fatalf("Generate() second result = %+v, want idempotent no-op", second)
	}
}

func TestGenerateReturnsUsefulLookupErrors(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales", "")
	writeTestEntity(t, root, "sales", "lead")

	tests := []struct {
		name       string
		appName    string
		entityName string
		want       string
	}{
		{name: "unknown app", appName: "support", entityName: "lead", want: `app "support" not found`},
		{name: "unknown entity", appName: "sales", entityName: "deal", want: `entity "deal" not found in app "sales"`},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			_, err := Generate(root, tt.appName, tt.entityName)
			if err == nil {
				t.Fatal("Generate() error = nil, want lookup error")
			}
			if !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("Generate() error = %q, want substring %q", err.Error(), tt.want)
			}
		})
	}
}

func TestGenerateFailsSafelyForExistingHookWithoutRegister(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales", "")
	writeTestEntity(t, root, "sales", "lead")
	hookPath := filepath.Join(root, "apps", "sales", "entities", "lead", "hooks.go")
	writeTestFile(t, hookPath, "package hooks\n")

	_, err := Generate(root, "sales", "lead")
	if err == nil {
		t.Fatal("Generate() error = nil, want existing hook error")
	}
	for _, want := range []string{"hooks.go exists but does not expose Register", "dygo.RecordHookRegistry"} {
		if !strings.Contains(err.Error(), want) {
			t.Fatalf("Generate() error = %q, want substring %q", err.Error(), want)
		}
	}
	assertPathMissing(t, filepath.Join(root, "cmd", "dygo", "main.go"))
}

func TestGenerateFailsSafelyForCustomRunner(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales", "")
	writeTestEntity(t, root, "sales", "lead")
	writeTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"), "package main\n")

	_, err := Generate(root, "sales", "lead")
	if err == nil {
		t.Fatal("Generate() error = nil, want custom runner error")
	}
	for _, want := range []string{"cmd/dygo/main.go exists and is not dygo-generated", `salesleadhooks "example.com/acme/apps/sales/entities/lead"`} {
		if !strings.Contains(err.Error(), want) {
			t.Fatalf("Generate() error = %q, want substring %q", err.Error(), want)
		}
	}
	assertPathMissing(t, filepath.Join(root, "apps", "sales", "entities", "lead", "hooks.go"))
}

func TestGenerateUsesEntityBundleAndKebabEntityName(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales", "")
	writeTestEntity(t, root, "sales", "lead-status")

	_, err := Generate(root, "sales", "lead-status")
	if err != nil {
		t.Fatalf("Generate() error = %v, want nil", err)
	}

	hookSource := readTestFile(t, filepath.Join(root, "apps", "sales", "entities", "lead-status", "hooks.go"))
	for _, want := range []string{"func Register(registry dygo.RecordHookRegistry) error", "beforeCreateLeadStatus", "afterCreateLeadStatus", "beforeUpdateLeadStatus", "afterUpdateLeadStatus"} {
		if !strings.Contains(hookSource, want) {
			t.Fatalf("hook source = %q, want substring %q", hookSource, want)
		}
	}
	runnerSource := readTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"))
	if !strings.Contains(runnerSource, `salesleadstatushooks "example.com/acme/apps/sales/entities/lead-status"`) {
		t.Fatalf("runner source = %q, want Entity hook import", runnerSource)
	}
}

func TestGeneratePreservesExistingEntityHookFile(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales", "")
	writeTestEntity(t, root, "sales", "lead")
	existing := `package hooks

import "github.com/hapyco/dygo/pkg/dygo"

func Register(registry dygo.RecordHookRegistry) error {
	return nil
}
`
	hookPath := filepath.Join(root, "apps", "sales", "entities", "lead", "hooks.go")
	writeTestFile(t, hookPath, existing)

	result, err := Generate(root, "sales", "lead")
	if err != nil {
		t.Fatalf("Generate() error = %v, want nil", err)
	}
	if result.HookFileCreated {
		t.Fatal("HookFileCreated = true, want existing hook preserved")
	}
	if got := readTestFile(t, hookPath); got != existing {
		t.Fatalf("hook source changed:\n%s", got)
	}
	runnerSource := readTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"))
	if !strings.Contains(runnerSource, "salesleadhooks.Register") {
		t.Fatalf("runner source = %q, want existing hook registrar call", runnerSource)
	}
}

func TestGeneratePreservesLegacyGeneratedHeaderHookFile(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales", "")
	writeTestEntity(t, root, "sales", "lead")
	existing := `// Code generated by dygo generate hook; DO NOT EDIT.

package hooks

import "github.com/hapyco/dygo/pkg/dygo"

func Register(registry dygo.RecordHookRegistry) error {
	return nil
}
`
	hookPath := filepath.Join(root, "apps", "sales", "entities", "lead", "hooks.go")
	writeTestFile(t, hookPath, existing)

	result, err := GenerateWithOptions(GenerateOptions{Root: root, AppName: "sales", EntityName: "lead", Force: true})
	if err != nil {
		t.Fatalf("GenerateWithOptions(force) error = %v, want nil", err)
	}
	if result.HookFileStatus != "existing" {
		t.Fatalf("HookFileStatus = %q, want existing", result.HookFileStatus)
	}
	if got := readTestFile(t, hookPath); got != existing {
		t.Fatalf("legacy hook source changed:\n%s", got)
	}
}

func TestGenerateRunnerOrdersMultipleHookApps(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "support", "")
	writeTestEntity(t, root, "support", "ticket")
	writeTestApp(t, root, "sales", "")
	writeTestEntity(t, root, "sales", "lead")

	if _, err := Generate(root, "support", "ticket"); err != nil {
		t.Fatalf("Generate(support ticket) error = %v, want nil", err)
	}
	if _, err := Generate(root, "sales", "lead"); err != nil {
		t.Fatalf("Generate(sales lead) error = %v, want nil", err)
	}

	runnerSource := readTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"))
	assertBefore(t, runnerSource, `salesleadhooks "example.com/acme/apps/sales/entities/lead"`, `supporttickethooks "example.com/acme/apps/support/entities/ticket"`)
	assertBefore(t, runnerSource, "salesleadhooks.Register", "supporttickethooks.Register")
}

func TestGenerateOutputCompilesInProject(t *testing.T) {
	repoRoot := repositoryRoot(t)
	root := newTestProjectWithBody(t, `module example.com/acme

go 1.26.2

require github.com/hapyco/dygo v0.0.0

replace github.com/hapyco/dygo => `+filepath.ToSlash(repoRoot)+`
`)
	copyTestFile(t, filepath.Join(repoRoot, "go.sum"), filepath.Join(root, "go.sum"))
	writeTestApp(t, root, "sales", "")
	writeTestEntity(t, root, "sales", "lead")

	if _, err := Generate(root, "sales", "lead"); err != nil {
		t.Fatalf("Generate() error = %v, want nil", err)
	}

	runGoCommand(t, root, "mod", "tidy")
	runGoCommand(t, root, "test", "./...")
}

func newTestProject(t *testing.T, modulePath string) string {
	t.Helper()
	return newTestProjectWithBody(t, "module "+modulePath+"\n\ngo 1.26.2\n")
}

func newTestProjectWithBody(t *testing.T, goMod string) string {
	t.Helper()
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "dygo.yml"), "name: test\n")
	writeTestFile(t, filepath.Join(root, "go.mod"), goMod)
	return root
}

func writeTestApp(t *testing.T, root string, name string, extra string) {
	t.Helper()
	body := "name: " + name + "\nlabel: " + strings.ToUpper(name[:1]) + name[1:] + "\nversion: 0.1.0\n"
	if strings.TrimSpace(extra) != "" {
		body += strings.TrimSpace(extra) + "\n"
	}
	writeTestFile(t, filepath.Join(root, "apps", name, "app.yml"), body)
}

func writeTestEntity(t *testing.T, root string, appName string, entityName string) {
	t.Helper()
	body := "label: " + strings.ToUpper(entityName[:1]) + entityName[1:] + "\nname:\n  strategy: random\nfields:\n  - name: title\n    label: Title\n    type: text\n"
	writeTestFile(t, filepath.Join(root, "apps", appName, "entities", entityName, entityName+".entity.yml"), body)
}

func writeTestFile(t *testing.T, path string, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("MkdirAll(%s) error = %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("WriteFile(%s) error = %v", path, err)
	}
}

func readTestFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(%s) error = %v", path, err)
	}
	return string(data)
}

func copyTestFile(t *testing.T, source string, destination string) {
	t.Helper()
	data, err := os.ReadFile(source)
	if err != nil {
		t.Fatalf("ReadFile(%s) error = %v", source, err)
	}
	writeTestFile(t, destination, string(data))
}

func assertPathMissing(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err == nil {
		t.Fatalf("%s exists, want missing", path)
	} else if !os.IsNotExist(err) {
		t.Fatalf("Stat(%s) error = %v, want missing", path, err)
	}
}

func assertBefore(t *testing.T, source string, first string, second string) {
	t.Helper()
	firstIndex := strings.Index(source, first)
	if firstIndex == -1 {
		t.Fatalf("source = %q, missing %q", source, first)
	}
	secondIndex := strings.Index(source, second)
	if secondIndex == -1 {
		t.Fatalf("source = %q, missing %q", source, second)
	}
	if firstIndex >= secondIndex {
		t.Fatalf("source order invalid: %q should appear before %q in\n%s", first, second, source)
	}
}

func repositoryRoot(t *testing.T) string {
	t.Helper()
	cmd := exec.Command("git", "rev-parse", "--show-toplevel")
	output, err := cmd.Output()
	if err != nil {
		t.Fatalf("git rev-parse --show-toplevel error = %v", err)
	}
	return string(bytes.TrimSpace(output))
}

func runGoCommand(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("go", args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off")
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("go %s in generated project error = %v\n%s", strings.Join(args, " "), err, string(output))
	}
}
