// Package runnergen renders generated project runner wiring for app code.
package runnergen

import (
	"bufio"
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/hapyco/dygo/internal/app/manifest"
	"github.com/hapyco/dygo/internal/entity/catalog"
	"github.com/hapyco/dygo/internal/jobs"
	"github.com/hapyco/dygo/internal/project"
	"github.com/hapyco/dygo/internal/shape"
)

const GeneratedHeader = "// Code generated by dygo generate; DO NOT EDIT."

// HookTarget forces one hook package into runner output before it exists on disk.
type HookTarget struct {
	AppName    string
	EntityName string
}

// JobTarget forces one Job package into runner output before it exists on disk.
type JobTarget struct {
	AppName string
	JobName string
}

// RenderOptions controls generated runner output.
type RenderOptions struct {
	HookTarget HookTarget
	JobTarget  JobTarget
}

// RunnerUpdate describes a generated project runner update.
type RunnerUpdate struct {
	RunnerFile string
	Source     []byte
}

// HookFile describes one discovered Entity hook file.
type HookFile struct {
	AppName     string
	EntityName  string
	Path        string
	ImportPath  string
	Alias       string
	HasRegister bool
	RunnerWired bool
}

// JobFile describes one discovered Job runner file.
type JobFile struct {
	AppName     string
	JobName     string
	Path        string
	ImportPath  string
	Alias       string
	HasRun      bool
	RunnerWired bool
}

// Render renders the project runner for discovered hooks and Jobs.
func Render(root string, options RenderOptions) (RunnerUpdate, error) {
	root = filepath.Clean(root)
	if err := RequireGeneratedProjectRoot(root); err != nil {
		return RunnerUpdate{}, err
	}
	modulePath, err := ReadModulePath(root)
	if err != nil {
		return RunnerUpdate{}, err
	}
	metadata, err := project.LoadMetadata(root)
	if err != nil {
		return RunnerUpdate{}, err
	}

	runnerFile := filepath.Join(root, "cmd", "dygo", "main.go")
	if err := PreflightGeneratedFile(runnerFile, UpgradeManualSnippet()); err != nil {
		return RunnerUpdate{}, err
	}
	hookFiles, err := CollectHookFiles(root, modulePath, metadata.Apps, metadata.Entities, options.HookTarget)
	if err != nil {
		return RunnerUpdate{}, err
	}
	jobFiles, err := CollectJobFiles(root, modulePath, metadata.Apps, options.JobTarget)
	if err != nil {
		return RunnerUpdate{}, err
	}
	runnerSource, err := RenderSource(hookFiles, jobFiles)
	if err != nil {
		return RunnerUpdate{}, err
	}
	return RunnerUpdate{RunnerFile: runnerFile, Source: runnerSource}, nil
}

// Update writes the generated project runner when its content changes.
func Update(root string) (RunnerUpdate, bool, error) {
	update, err := Render(root, RenderOptions{})
	if err != nil {
		return RunnerUpdate{}, false, err
	}
	if err := os.MkdirAll(filepath.Dir(update.RunnerFile), 0o755); err != nil {
		return RunnerUpdate{}, false, fmt.Errorf("create runner directory %s: %w", filepath.Dir(update.RunnerFile), err)
	}
	written, err := WriteFileIfChanged(update.RunnerFile, update.Source)
	if err != nil {
		return RunnerUpdate{}, false, err
	}
	return update, written, nil
}

// DiscoverHooks returns Entity hook files found in canonical Entity bundles.
func DiscoverHooks(root string) ([]HookFile, error) {
	root = filepath.Clean(root)
	if err := RequireGeneratedProjectRoot(root); err != nil {
		return nil, err
	}
	modulePath, err := ReadModulePath(root)
	if err != nil {
		return nil, err
	}
	metadata, err := project.LoadMetadata(root)
	if err != nil {
		return nil, err
	}
	hookFiles, err := CollectHookFiles(root, modulePath, metadata.Apps, metadata.Entities, HookTarget{})
	if err != nil {
		return nil, err
	}
	MarkHookRunnerWiring(filepath.Join(root, "cmd", "dygo", "main.go"), hookFiles)
	return hookFiles, nil
}

// DiscoverJobs returns Job runner files found in app Job bundles.
func DiscoverJobs(root string) ([]JobFile, error) {
	root = filepath.Clean(root)
	if err := RequireGeneratedProjectRoot(root); err != nil {
		return nil, err
	}
	modulePath, err := ReadModulePath(root)
	if err != nil {
		return nil, err
	}
	apps, err := project.LoadApps(root)
	if err != nil {
		return nil, err
	}
	jobFiles, err := CollectJobFiles(root, modulePath, apps, JobTarget{})
	if err != nil {
		return nil, err
	}
	MarkJobRunnerWiring(filepath.Join(root, "cmd", "dygo", "main.go"), jobFiles)
	return jobFiles, nil
}

// RequireGeneratedProjectRoot verifies a generated dygo project marker.
func RequireGeneratedProjectRoot(root string) error {
	marker := filepath.Join(root, project.MarkerFile)
	info, err := os.Stat(marker)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("generation requires a dygo project root with %s", project.MarkerFile)
		}
		return fmt.Errorf("stat dygo project marker %s: %w", marker, err)
	}
	if info.IsDir() {
		return fmt.Errorf("dygo project marker %s must be a file", marker)
	}
	return nil
}

// ReadModulePath reads the current module path from go.mod.
func ReadModulePath(root string) (string, error) {
	path := filepath.Join(root, "go.mod")
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read go module %s: %w", path, err)
	}
	scanner := bufio.NewScanner(bytes.NewReader(data))
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) >= 2 && fields[0] == "module" {
			return fields[1], nil
		}
	}
	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("scan go module %s: %w", path, err)
	}
	return "", fmt.Errorf("go module %s is missing a module directive", path)
}

// IsProjectOwnedApp reports whether appDir is a direct apps/<app> child.
func IsProjectOwnedApp(root string, appDir string) bool {
	relative, err := filepath.Rel(root, appDir)
	if err != nil {
		return false
	}
	parts := strings.Split(filepath.ToSlash(relative), "/")
	return len(parts) == 2 && parts[0] == "apps" && parts[1] != ""
}

// PreflightGeneratedFile rejects custom generated-runner destinations.
func PreflightGeneratedFile(path string, manualSnippet string) error {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("stat %s: %w", path, err)
	}
	if info.IsDir() || !info.Mode().IsRegular() {
		return fmt.Errorf("%s must be a regular file", path)
	}
	generated, err := IsGeneratedFile(path)
	if err != nil {
		return err
	}
	if !generated {
		return fmt.Errorf("%s exists and is not dygo-generated; add wiring manually:\n%s", path, strings.TrimSpace(manualSnippet))
	}
	return nil
}

// GeneratedFileStatus reports how writing source would affect path.
func GeneratedFileStatus(path string, source []byte, dryRun bool) (string, error) {
	existing, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			if dryRun {
				return "would create", nil
			}
			return "created", nil
		}
		return "", fmt.Errorf("read %s: %w", path, err)
	}
	if bytes.Equal(existing, source) {
		return "unchanged", nil
	}
	if dryRun {
		return "would update", nil
	}
	return "updated", nil
}

// IsGeneratedFile reports whether a file is dygo-managed generated code.
func IsGeneratedFile(path string) (bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return false, fmt.Errorf("read %s: %w", path, err)
	}
	source := string(data)
	return strings.Contains(source, "Code generated by dygo") && strings.Contains(source, "DO NOT EDIT."), nil
}

// CollectHookFiles returns hook files for existing hooks plus an optional target.
func CollectHookFiles(root string, modulePath string, apps []manifest.LoadedApp, entities []catalog.LoadedEntity, target HookTarget) ([]HookFile, error) {
	appsByName := map[string]manifest.LoadedApp{}
	for _, app := range apps {
		if IsProjectOwnedApp(root, app.Dir) {
			appsByName[app.Manifest.Name] = app
		}
	}

	var hookFiles []HookFile
	for _, entity := range entities {
		if entity.IsCollection() {
			continue
		}
		app, ok := appsByName[entity.AppName]
		if !ok {
			continue
		}
		hookPath := filepath.Join(filepath.Dir(entity.Path), shape.EntityHooksFile)
		include := target.AppName == entity.AppName && target.EntityName == entity.Entity.Name
		exists, hasRegister, err := InspectFunctionFile(hookPath, "Register")
		if err != nil {
			return nil, err
		}
		if include {
			hasRegister = true
		}
		if !include && !exists {
			continue
		}
		importPath, err := ImportPathForDir(root, modulePath, filepath.Dir(hookPath))
		if err != nil {
			return nil, err
		}
		hookFiles = append(hookFiles, HookFile{
			AppName:     app.Manifest.Name,
			EntityName:  entity.Entity.Name,
			Path:        hookPath,
			ImportPath:  importPath,
			HasRegister: hasRegister,
		})
	}
	sort.SliceStable(hookFiles, func(i, j int) bool {
		if hookFiles[i].AppName != hookFiles[j].AppName {
			return hookFiles[i].AppName < hookFiles[j].AppName
		}
		return hookFiles[i].EntityName < hookFiles[j].EntityName
	})
	assignHookImportAliases(hookFiles)
	return hookFiles, nil
}

// CollectJobFiles returns Job runner files for existing jobs plus an optional target.
func CollectJobFiles(root string, modulePath string, apps []manifest.LoadedApp, target JobTarget) ([]JobFile, error) {
	appsByName := map[string]manifest.LoadedApp{}
	for _, app := range apps {
		if IsProjectOwnedApp(root, app.Dir) {
			appsByName[app.Manifest.Name] = app
		}
	}

	var jobFiles []JobFile
	for _, app := range appsByName {
		jobsDir := filepath.Join(app.Dir, shape.AppJobsDir)
		entries, err := os.ReadDir(jobsDir)
		if err != nil && !os.IsNotExist(err) {
			return nil, fmt.Errorf("read jobs for app %q from %s: %w", app.Manifest.Name, jobsDir, err)
		}
		targetIncluded := false
		for _, entry := range entries {
			if !entry.IsDir() {
				continue
			}
			include := target.AppName == app.Manifest.Name && target.JobName == entry.Name()
			if include {
				targetIncluded = true
				jobFile, err := jobFileFor(root, modulePath, app.Manifest.Name, filepath.Join(jobsDir, entry.Name()), entry.Name(), true)
				if err != nil {
					return nil, err
				}
				jobFiles = append(jobFiles, jobFile)
				continue
			}
			jobPath := filepath.Join(jobsDir, entry.Name(), shape.JobMetadataFile)
			info, err := os.Stat(jobPath)
			if err != nil {
				if os.IsNotExist(err) {
					continue
				}
				return nil, fmt.Errorf("stat job metadata for app %q from %s: %w", app.Manifest.Name, jobPath, err)
			}
			if !info.Mode().IsRegular() {
				continue
			}
			loaded, err := jobs.LoadFile(jobPath)
			if err != nil {
				return nil, err
			}
			jobFile, err := jobFileFor(root, modulePath, app.Manifest.Name, filepath.Dir(jobPath), loaded.Name, false)
			if err != nil {
				return nil, err
			}
			jobFiles = append(jobFiles, jobFile)
		}
		if target.AppName == app.Manifest.Name && target.JobName != "" && !targetIncluded {
			jobDir := filepath.Join(jobsDir, target.JobName)
			jobFile, err := jobFileFor(root, modulePath, app.Manifest.Name, jobDir, target.JobName, true)
			if err != nil {
				return nil, err
			}
			jobFiles = append(jobFiles, jobFile)
		}
	}
	sort.SliceStable(jobFiles, func(i, j int) bool {
		if jobFiles[i].AppName != jobFiles[j].AppName {
			return jobFiles[i].AppName < jobFiles[j].AppName
		}
		return jobFiles[i].JobName < jobFiles[j].JobName
	})
	assignJobImportAliases(jobFiles)
	return jobFiles, nil
}

func jobFileFor(root string, modulePath string, appName string, jobDir string, jobName string, includeTarget bool) (JobFile, error) {
	runPath := filepath.Join(jobDir, shape.JobRunFile)
	_, hasRun, err := InspectFunctionFile(runPath, "Run")
	if err != nil {
		return JobFile{}, err
	}
	if includeTarget {
		hasRun = true
	}
	importPath, err := ImportPathForDir(root, modulePath, jobDir)
	if err != nil {
		return JobFile{}, err
	}
	return JobFile{
		AppName:    appName,
		JobName:    jobName,
		Path:       runPath,
		ImportPath: importPath,
		HasRun:     hasRun,
	}, nil
}

// InspectFunctionFile reports whether path exists and exposes a top-level function.
func InspectFunctionFile(path string, functionName string) (bool, bool, error) {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, false, nil
		}
		return false, false, fmt.Errorf("stat %s: %w", path, err)
	}
	if info.IsDir() || !info.Mode().IsRegular() {
		return true, false, fmt.Errorf("%s must be a regular file", path)
	}

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return true, false, fmt.Errorf("parse %s: %w", path, err)
	}
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if ok && fn.Recv == nil && fn.Name.Name == functionName {
			return true, true, nil
		}
	}
	return true, false, nil
}

// ImportPathForDir builds a module import path for a project-owned directory.
func ImportPathForDir(root string, modulePath string, dir string) (string, error) {
	relative, err := filepath.Rel(root, dir)
	if err != nil {
		return "", fmt.Errorf("resolve import path for %s: %w", dir, err)
	}
	if strings.HasPrefix(relative, "..") {
		return "", fmt.Errorf("directory %s is outside project root", dir)
	}
	return strings.TrimRight(modulePath, "/") + "/" + filepath.ToSlash(relative), nil
}

// MarkHookRunnerWiring annotates hook files with current runner state.
func MarkHookRunnerWiring(runnerFile string, hookFiles []HookFile) {
	data, err := os.ReadFile(runnerFile)
	if err != nil {
		return
	}
	source := string(data)
	for index := range hookFiles {
		hookFiles[index].RunnerWired = strings.Contains(source, strconv.Quote(hookFiles[index].ImportPath)) && strings.Contains(source, hookFiles[index].Alias+".Register")
	}
}

// MarkJobRunnerWiring annotates Job files with current runner state.
func MarkJobRunnerWiring(runnerFile string, jobFiles []JobFile) {
	data, err := os.ReadFile(runnerFile)
	if err != nil {
		return
	}
	source := string(data)
	for index := range jobFiles {
		jobFiles[index].RunnerWired = strings.Contains(source, strconv.Quote(jobFiles[index].ImportPath)) && strings.Contains(source, jobFiles[index].Alias+".Run")
	}
}

// RenderSource renders the project runner source.
func RenderSource(hookFiles []HookFile, jobFiles []JobFile) ([]byte, error) {
	wiredHooks := make([]HookFile, 0, len(hookFiles))
	for _, hook := range hookFiles {
		if hook.HasRegister {
			wiredHooks = append(wiredHooks, hook)
		}
	}
	wiredJobs := make([]JobFile, 0, len(jobFiles))
	for _, job := range jobFiles {
		if job.HasRun {
			wiredJobs = append(wiredJobs, job)
		}
	}

	var builder strings.Builder
	builder.WriteString(GeneratedHeader)
	builder.WriteString("\n\npackage main\n\n")
	builder.WriteString("import (\n")
	builder.WriteString("\t\"context\"\n")
	builder.WriteString("\t\"fmt\"\n")
	builder.WriteString("\t\"os\"\n")
	builder.WriteString("\t\"os/signal\"\n")
	builder.WriteString("\t\"syscall\"\n\n")
	for _, hook := range wiredHooks {
		builder.WriteString(fmt.Sprintf("\t%s %q\n", hook.Alias, hook.ImportPath))
	}
	for _, job := range wiredJobs {
		builder.WriteString(fmt.Sprintf("\t%s %q\n", job.Alias, job.ImportPath))
	}
	if len(wiredHooks) > 0 || len(wiredJobs) > 0 {
		builder.WriteString("\t\"github.com/hapyco/dygo/pkg/dygo\"\n")
	}
	builder.WriteString("\tdygoruntime \"github.com/hapyco/dygo/pkg/dygo/runtime\"\n")
	builder.WriteString(")\n\n")
	builder.WriteString("func main() {\n")
	builder.WriteString("\tctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)\n")
	builder.WriteString("\tdefer stop()\n\n")
	builder.WriteString("\terr := dygoruntime.Run(ctx, os.Args[1:], os.Stdin, os.Stdout, os.Stderr")
	if len(wiredHooks) == 0 && len(wiredJobs) == 0 {
		builder.WriteString(", dygoruntime.Options{})\n")
	} else {
		builder.WriteString(", dygoruntime.Options{\n")
		if len(wiredHooks) > 0 {
			builder.WriteString("\t\tRecordHooks: []dygo.RecordHookRegistrar{\n")
			for _, hook := range wiredHooks {
				builder.WriteString(fmt.Sprintf("\t\t\t%s.Register,\n", hook.Alias))
			}
			builder.WriteString("\t\t},\n")
		}
		if len(wiredJobs) > 0 {
			builder.WriteString("\t\tJobs: []dygo.JobRegistrar{\n")
			for _, job := range wiredJobs {
				builder.WriteString("\t\t\tfunc(registry dygo.JobRegistry) error {\n")
				builder.WriteString(fmt.Sprintf("\t\t\t\treturn registry.RegisterJob(%q, %q, %s.Run)\n", job.AppName, job.JobName, job.Alias))
				builder.WriteString("\t\t\t},\n")
			}
			builder.WriteString("\t\t},\n")
		}
		builder.WriteString("\t})\n")
	}
	builder.WriteString("\tif err != nil {\n")
	builder.WriteString("\t\tfmt.Fprintln(os.Stderr, err)\n")
	builder.WriteString("\t\tos.Exit(1)\n")
	builder.WriteString("\t}\n")
	builder.WriteString("}\n")
	return FormatGoSource([]byte(builder.String()))
}

// FormatGoSource formats generated Go source.
func FormatGoSource(source []byte) ([]byte, error) {
	formatted, err := format.Source(source)
	if err != nil {
		return nil, fmt.Errorf("format generated Go source: %w", err)
	}
	return formatted, nil
}

// WriteFileIfChanged writes data only when path differs.
func WriteFileIfChanged(path string, data []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, data) {
		return false, nil
	}
	if err != nil && !os.IsNotExist(err) {
		return false, fmt.Errorf("read %s: %w", path, err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return false, fmt.Errorf("write %s: %w", path, err)
	}
	return true, nil
}

// HookManualSnippet returns wiring help for a custom project runner.
func HookManualSnippet(root string, modulePath string, appName string, entityName string, entityDir string) string {
	alias := LowerIdentifier(appName+"-"+entityName) + "hooks"
	importPath, err := ImportPathForDir(root, modulePath, entityDir)
	if err != nil {
		importPath = strings.TrimRight(modulePath, "/") + "/" + filepath.ToSlash(filepath.Clean(entityDir))
	}
	if alias == "hooks" {
		alias = "entityhooks"
	}
	return fmt.Sprintf(`import %s %q

RecordHooks: []dygo.RecordHookRegistrar{%s.Register},`, alias, importPath, alias)
}

// JobManualSnippet returns wiring help for a custom project runner.
func JobManualSnippet(root string, modulePath string, appName string, jobName string, jobDir string) string {
	alias := LowerIdentifier(appName+"-"+jobName) + "job"
	importPath, err := ImportPathForDir(root, modulePath, jobDir)
	if err != nil {
		importPath = strings.TrimRight(modulePath, "/") + "/" + filepath.ToSlash(filepath.Clean(jobDir))
	}
	if alias == "job" {
		alias = "appjob"
	}
	return fmt.Sprintf(`import %s %q

Jobs: []dygo.JobRegistrar{
	func(registry dygo.JobRegistry) error {
		return registry.RegisterJob(%q, %q, %s.Run)
	},
},`, alias, importPath, appName, jobName, alias)
}

// UpgradeManualSnippet returns generic wiring help for custom runners.
func UpgradeManualSnippet() string {
	return `cmd/dygo/main.go is custom. Import app hook and Job packages manually and call pkg/dygo/runtime.Run with runtime.Options{RecordHooks: ..., Jobs: ...}.`
}

// ExportedIdentifier returns a Go exported identifier from a kebab key.
func ExportedIdentifier(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	var builder strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		runes := []rune(part)
		builder.WriteRune(unicode.ToUpper(runes[0]))
		for _, r := range runes[1:] {
			builder.WriteRune(r)
		}
	}
	if builder.Len() == 0 {
		return "Name"
	}
	return builder.String()
}

// LowerIdentifier returns a lower-case Go import alias base.
func LowerIdentifier(value string) string {
	var builder strings.Builder
	for _, r := range value {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			builder.WriteRune(unicode.ToLower(r))
		}
	}
	return builder.String()
}

func assignHookImportAliases(hookFiles []HookFile) {
	used := map[string]int{}
	for index := range hookFiles {
		base := LowerIdentifier(hookFiles[index].AppName+"-"+hookFiles[index].EntityName) + "hooks"
		if base == "hooks" {
			base = "entityhooks"
		}
		count := used[base]
		used[base] = count + 1
		if count == 0 {
			hookFiles[index].Alias = base
			continue
		}
		hookFiles[index].Alias = fmt.Sprintf("%s%d", base, count+1)
	}
}

func assignJobImportAliases(jobFiles []JobFile) {
	used := map[string]int{}
	for index := range jobFiles {
		base := LowerIdentifier(jobFiles[index].AppName+"-"+jobFiles[index].JobName) + "job"
		if base == "job" {
			base = "appjob"
		}
		count := used[base]
		used[base] = count + 1
		if count == 0 {
			jobFiles[index].Alias = base
			continue
		}
		jobFiles[index].Alias = fmt.Sprintf("%s%d", base, count+1)
	}
}
