// Package projectgen generates dygo project scaffolds.
package projectgen

import (
	"context"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"unicode"

	"github.com/dygo-dev/dygo/internal/project"
	"github.com/dygo-dev/dygo/internal/secrets"
	"github.com/dygo-dev/dygo/internal/studio"
)

const (
	dygoModulePath  = "github.com/dygo-dev/dygo"
	defaultGo       = "1.26.2"
	developmentPort = 6790

	generatedHeader = "// Code generated by dygo new; DO NOT EDIT."
)

// Options configures project generation.
type Options struct {
	Name          string
	ModulePath    string
	WorkingDir    string
	DygoVersion   string
	FrameworkRoot string
	SkipTidy      bool
	DatabaseURL   string

	// StudioAssets is for tests and custom project generators. Normal builds use
	// framework build output or bundled release assets.
	StudioAssets fs.FS
}

// Result describes a generated dygo project.
type Result struct {
	Name         string
	Label        string
	ModulePath   string
	Path         string
	DatabaseURL  string
	TidyRun      bool
	StudioCached bool
	StudioSource string
}

type dygoDependency struct {
	Version string
	Replace string
}

// Generate creates a new dygo project.
func Generate(ctx context.Context, options Options) (Result, error) {
	if ctx == nil {
		return Result{}, fmt.Errorf("context is required")
	}
	workingDir := strings.TrimSpace(options.WorkingDir)
	if workingDir == "" {
		workingDir = "."
	}
	workingDir, err := filepath.Abs(workingDir)
	if err != nil {
		return Result{}, fmt.Errorf("resolve working directory: %w", err)
	}
	name, err := NormalizeName(options.Name)
	if err != nil {
		return Result{}, err
	}
	modulePath := strings.TrimSpace(options.ModulePath)
	if modulePath == "" {
		modulePath = name
	}
	if err := validateModulePath(modulePath); err != nil {
		return Result{}, err
	}
	dep, err := resolveDygoDependency(options, workingDir)
	if err != nil {
		return Result{}, err
	}

	target := filepath.Join(workingDir, name)
	if _, err := os.Stat(target); err == nil {
		return Result{}, fmt.Errorf("target project path %s already exists", target)
	} else if !os.IsNotExist(err) {
		return Result{}, fmt.Errorf("stat target project path %s: %w", target, err)
	}

	label := LabelForName(name)
	databaseURL := strings.TrimSpace(options.DatabaseURL)
	if databaseURL == "" {
		databaseURL = defaultDatabaseURL(name)
	}

	if err := writeProjectFiles(target, name, label, modulePath, dep); err != nil {
		return Result{}, err
	}
	store := secrets.NewStore(target)
	if _, err := store.Init(false); err != nil {
		return Result{}, fmt.Errorf("initialize encrypted secrets: %w", err)
	}
	if err := store.Set(secrets.EnvironmentDevelopment, "DATABASE_URL", databaseURL); err != nil {
		return Result{}, fmt.Errorf("write development database secret: %w", err)
	}
	studioCached, studioSource, err := installStudioCache(target, options, dep)
	if err != nil {
		return Result{}, err
	}

	result := Result{
		Name:         name,
		Label:        label,
		ModulePath:   modulePath,
		Path:         target,
		DatabaseURL:  databaseURL,
		StudioCached: studioCached,
		StudioSource: studioSource,
	}
	if !options.SkipTidy {
		if err := runGoModTidy(ctx, target); err != nil {
			return Result{}, err
		}
		result.TidyRun = true
	}
	return result, nil
}

// NormalizeName converts a project display name into a dygo kebab-case name.
func NormalizeName(value string) (string, error) {
	value = strings.TrimSpace(value)
	if value == "" {
		return "", fmt.Errorf("project name is required")
	}
	var builder strings.Builder
	lastDash := false
	for _, r := range value {
		switch {
		case isASCIIAlpha(r) || isASCIIDigit(r):
			builder.WriteRune(lowerASCII(r))
			lastDash = false
		default:
			if builder.Len() > 0 && !lastDash {
				builder.WriteRune('-')
				lastDash = true
			}
		}
	}
	name := strings.Trim(builder.String(), "-")
	if name == "" {
		return "", fmt.Errorf("project name %q must contain letters or numbers", value)
	}
	first, _ := firstRune(name)
	if !isASCIIAlpha(first) {
		return "", fmt.Errorf("project name %q must start with a letter after normalization", value)
	}
	return name, nil
}

func isASCIIAlpha(r rune) bool {
	return (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')
}

func isASCIIDigit(r rune) bool {
	return r >= '0' && r <= '9'
}

func lowerASCII(r rune) rune {
	if r >= 'A' && r <= 'Z' {
		return r + ('a' - 'A')
	}
	return r
}

// LabelForName converts a kebab-case project name into a display label.
func LabelForName(name string) string {
	parts := strings.Split(name, "-")
	for index, part := range parts {
		if part == "" {
			continue
		}
		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		parts[index] = string(runes)
	}
	return strings.Join(parts, " ")
}

func firstRune(value string) (rune, bool) {
	for _, r := range value {
		return r, true
	}
	return 0, false
}

func validateModulePath(modulePath string) error {
	if strings.TrimSpace(modulePath) == "" {
		return fmt.Errorf("module path is required")
	}
	if strings.ContainsAny(modulePath, " \t\r\n") {
		return fmt.Errorf("module path %q must not contain whitespace", modulePath)
	}
	return nil
}

func resolveDygoDependency(options Options, workingDir string) (dygoDependency, error) {
	version := strings.TrimSpace(options.DygoVersion)
	if version == "" {
		version = "dev"
	}
	if version != "dev" {
		return dygoDependency{Version: version}, nil
	}
	frameworkRoot := strings.TrimSpace(options.FrameworkRoot)
	if frameworkRoot == "" {
		root, err := project.DiscoverRoot(workingDir)
		if err == nil && root.Marker == "framework-repo" {
			frameworkRoot = root.Path
		}
	}
	if frameworkRoot == "" {
		return dygoDependency{}, fmt.Errorf("cannot resolve dygo module version for dev build; run dygo new from the framework checkout or use a release build")
	}
	frameworkRoot, err := filepath.Abs(frameworkRoot)
	if err != nil {
		return dygoDependency{}, fmt.Errorf("resolve framework root: %w", err)
	}
	return dygoDependency{Version: "v0.0.0", Replace: frameworkRoot}, nil
}

func installStudioCache(root string, options Options, dep dygoDependency) (bool, string, error) {
	sources := make([]studio.Source, 0, 3)
	if options.StudioAssets != nil {
		sources = append(sources, studio.Source{Name: "configured Studio assets", FS: options.StudioAssets})
	}
	if dep.Replace != "" {
		source, ok, err := studio.SourceFromDir("framework Studio build", studio.FrameworkDistPath(dep.Replace))
		if err != nil {
			return false, "", fmt.Errorf("resolve framework Studio build: %w", err)
		}
		if ok {
			sources = append(sources, source)
		}
	}
	source, ok, err := studio.EmbeddedSource()
	if err != nil {
		return false, "", err
	}
	if ok {
		sources = append(sources, source)
	}
	cached, name, err := studio.InstallCache(root, sources...)
	if err != nil {
		return false, "", fmt.Errorf("install Studio assets: %w", err)
	}
	return cached, name, nil
}

func writeProjectFiles(root string, name string, label string, modulePath string, dep dygoDependency) error {
	dirs := []string{
		"apps/" + name + "/entities",
		"apps/" + name + "/permissions",
		"apps/" + name + "/hooks",
		"apps/" + name + "/fixtures",
		"apps/" + name + "/patches",
		"apps/" + name + "/docs",
		"apps/" + name + "/assets",
		"configs/secrets",
		"db",
		"docs",
		"var/storage/public",
		"var/storage/private",
		"var/backups",
		"var/logs",
		"var/tmp",
		"var/cache",
		"var/imports",
		"var/exports",
		".dygo/apps",
		".dygo/cache",
	}
	for _, dir := range dirs {
		if err := os.MkdirAll(filepath.Join(root, filepath.FromSlash(dir)), 0o755); err != nil {
			return fmt.Errorf("create directory %s: %w", dir, err)
		}
	}

	runner, err := runnerSource()
	if err != nil {
		return err
	}
	files := map[string]string{
		".gitignore":                      gitignoreSource(),
		"README.md":                       readmeSource(label),
		project.MarkerFile:                "name: " + name + "\n",
		"go.mod":                          goModSource(modulePath, dep),
		"cmd/dygo/main.go":                runner,
		"configs/dygo.yaml":               configSource(),
		"db/schema.sql":                   schemaSource(),
		"docs/index.md":                   docsIndexSource(label),
		"apps/" + name + "/app.yml":       appManifestSource(name, label),
		"apps/" + name + "/docs/index.md": "# " + label + " App\n",
	}
	for path, source := range files {
		if err := writeProjectFile(root, path, []byte(source), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func writeProjectFile(root string, path string, data []byte, mode os.FileMode) error {
	target := filepath.Join(root, filepath.FromSlash(path))
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return fmt.Errorf("create directory for %s: %w", path, err)
	}
	if err := os.WriteFile(target, data, mode); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func goModSource(modulePath string, dep dygoDependency) string {
	var builder strings.Builder
	builder.WriteString("module ")
	builder.WriteString(modulePath)
	builder.WriteString("\n\ngo ")
	builder.WriteString(defaultGo)
	builder.WriteString("\n\nrequire ")
	builder.WriteString(dygoModulePath)
	builder.WriteByte(' ')
	builder.WriteString(dep.Version)
	builder.WriteByte('\n')
	if dep.Replace != "" {
		builder.WriteString("\nreplace ")
		builder.WriteString(dygoModulePath)
		builder.WriteString(" => ")
		builder.WriteString(filepath.ToSlash(dep.Replace))
		builder.WriteByte('\n')
	}
	return builder.String()
}

func runnerSource() (string, error) {
	source := generatedHeader + `

package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	dygoruntime "github.com/dygo-dev/dygo/pkg/sdk/runtime"
)

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	if err := dygoruntime.Run(ctx, os.Args[1:], os.Stdin, os.Stdout, os.Stderr, dygoruntime.Options{}); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
`
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return "", fmt.Errorf("format generated runner: %w", err)
	}
	return string(formatted), nil
}

func appManifestSource(name string, label string) string {
	return fmt.Sprintf(`name: %s
label: %s
version: 0.1.0
description: %s app.
paths:
  entities: entities
  permissions: permissions
  hooks: hooks
  fixtures: fixtures
  patches: patches
  docs: docs
  assets: assets
`, name, label, label)
}

func configSource() string {
	return fmt.Sprintf(`server:
  host: 127.0.0.1
  port: %d
database:
  driver: postgres
  url:
    secret: DATABASE_URL
`, developmentPort)
}

func gitignoreSource() string {
	return `# dygo local secrets
master.key

# dygo runtime/cache data
.dygo/
var/

# Go artifacts
*.exe
*.exe~
*.dll
*.so
*.dylib
*.test
*.out
coverage.*
*.coverprofile

# Environment/editor files
.env
.DS_Store
`
}

func readmeSource(label string) string {
	return fmt.Sprintf(`# %s

Generated by dygo.

## Development

%s

The generated development database secret is encrypted in `+"`configs/secrets/development.age.yaml`"+`.
Do not commit `+"`master.key`"+`.
`, label, "```sh\n"+
		"dygo secrets edit\n"+
		"dygo db prepare\n"+
		"dygo serve\n"+
		"```")
}

func docsIndexSource(label string) string {
	return "# " + label + " Docs\n"
}

func schemaSource() string {
	return "-- Generated by dygo. Run `dygo db prepare` or `dygo migrate` to update this snapshot.\n"
}

func defaultDatabaseURL(name string) string {
	return "postgres://localhost/" + strings.ReplaceAll(name, "-", "_") + "_development?sslmode=disable"
}

func runGoModTidy(ctx context.Context, root string) error {
	cmd := exec.CommandContext(ctx, "go", "mod", "tidy")
	cmd.Dir = root
	cmd.Env = append(os.Environ(), "GOWORK=off")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("run go mod tidy in %s: %w: %s", root, err, strings.TrimSpace(string(output)))
	}
	return nil
}
