// Package jobgen generates Job scaffolds and project runner wiring.
package jobgen

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/hapyco/dygo/internal/app/manifest"
	"github.com/hapyco/dygo/internal/jobs"
	"github.com/hapyco/dygo/internal/project"
	"github.com/hapyco/dygo/internal/runnergen"
	"github.com/hapyco/dygo/internal/shape"
)

const jobMetadataMarker = "Code generated by dygo generate job"

// Result describes files touched by Job scaffold generation.
type Result struct {
	AppName string
	JobName string

	JobFile    string
	RunFile    string
	RunnerFile string

	JobFileStatus    string
	RunFileStatus    string
	RunnerFileStatus string

	JobFileCreated    bool
	RunFileCreated    bool
	RunnerFileWritten bool
}

// GenerateOptions controls Job scaffold generation.
type GenerateOptions struct {
	Root    string
	AppName string
	JobName string
	DryRun  bool
	Force   bool
}

// Generate creates a Job scaffold and updates generated runner wiring.
func Generate(root string, appName string, jobName string) (Result, error) {
	return GenerateWithOptions(GenerateOptions{Root: root, AppName: appName, JobName: jobName})
}

// GenerateWithOptions creates or previews a Job scaffold and runner wiring.
func GenerateWithOptions(options GenerateOptions) (Result, error) {
	root := filepath.Clean(options.Root)
	appName := strings.TrimSpace(options.AppName)
	jobName := strings.TrimSpace(options.JobName)
	if err := shape.ValidateMetadataName("app", appName); err != nil {
		return Result{}, err
	}
	if err := shape.ValidateMetadataName("job", jobName); err != nil {
		return Result{}, err
	}
	if err := runnergen.RequireGeneratedProjectRoot(root); err != nil {
		return Result{}, err
	}

	modulePath, err := runnergen.ReadModulePath(root)
	if err != nil {
		return Result{}, err
	}
	apps, err := project.LoadApps(root)
	if err != nil {
		return Result{}, err
	}
	app, ok := findApp(apps, appName)
	if !ok {
		return Result{}, fmt.Errorf("app %q not found", appName)
	}
	if !runnergen.IsProjectOwnedApp(root, app.Dir) {
		return Result{}, fmt.Errorf("app %q is not a project-owned app under apps/", appName)
	}

	jobDir := filepath.Join(app.Dir, shape.AppJobsDir, jobName)
	jobFile := filepath.Join(jobDir, shape.JobMetadataFile)
	runFile := filepath.Join(jobDir, shape.JobRunFile)
	runnerFile := filepath.Join(root, "cmd", "dygo", "main.go")

	if err := preflightDirectory(jobDir); err != nil {
		return Result{}, err
	}
	if err := preflightRegularFile(jobFile); err != nil {
		return Result{}, err
	}
	if err := preflightRegularFile(runFile); err != nil {
		return Result{}, err
	}
	if exists, hasRun, err := runnergen.InspectFunctionFile(runFile, "Run"); err != nil {
		return Result{}, err
	} else if exists && !hasRun {
		return Result{}, fmt.Errorf("%s exists but does not expose Run(ctx context.Context, job dygo.JobExecution) error", runFile)
	}
	if err := runnergen.PreflightGeneratedFile(runnerFile, runnergen.JobManualSnippet(root, modulePath, appName, jobName, jobDir)); err != nil {
		return Result{}, err
	}

	jobSource := renderJobMetadata(jobName)
	runSource, err := renderRunSource(appName, jobName)
	if err != nil {
		return Result{}, err
	}
	runnerUpdate, err := runnergen.Render(root, runnergen.RenderOptions{JobTarget: runnergen.JobTarget{AppName: appName, JobName: jobName}})
	if err != nil {
		return Result{}, err
	}

	jobStatus, err := jobFileStatus(jobFile, jobSource, options)
	if err != nil {
		return Result{}, err
	}
	runStatus, err := runFileStatus(runFile, options.DryRun)
	if err != nil {
		return Result{}, err
	}
	runnerStatus, err := runnergen.GeneratedFileStatus(runnerFile, runnerUpdate.Source, options.DryRun)
	if err != nil {
		return Result{}, err
	}
	result := Result{
		AppName:          appName,
		JobName:          jobName,
		JobFile:          jobFile,
		RunFile:          runFile,
		RunnerFile:       runnerFile,
		JobFileStatus:    jobStatus,
		RunFileStatus:    runStatus,
		RunnerFileStatus: runnerStatus,
		JobFileCreated:   jobStatus == "created",
		RunFileCreated:   runStatus == "created",
		RunnerFileWritten: runnerStatus == "created" ||
			runnerStatus == "updated",
	}
	if options.DryRun {
		return result, nil
	}
	if err := os.MkdirAll(jobDir, 0o755); err != nil {
		return Result{}, fmt.Errorf("create Job directory %s: %w", jobDir, err)
	}
	if jobStatus == "created" || jobStatus == "updated" {
		if err := os.WriteFile(jobFile, jobSource, 0o644); err != nil {
			return Result{}, fmt.Errorf("write job metadata %s: %w", jobFile, err)
		}
	}
	if runStatus == "created" {
		if err := os.WriteFile(runFile, runSource, 0o644); err != nil {
			return Result{}, fmt.Errorf("write job runner %s: %w", runFile, err)
		}
	}
	if err := os.MkdirAll(filepath.Dir(runnerFile), 0o755); err != nil {
		return Result{}, fmt.Errorf("create runner directory %s: %w", filepath.Dir(runnerFile), err)
	}
	written, err := runnergen.WriteFileIfChanged(runnerFile, runnerUpdate.Source)
	if err != nil {
		return Result{}, err
	}
	result.RunnerFileWritten = written
	if result.RunnerFileStatus == "" {
		result.RunnerFileStatus = writeStatus(written)
	}
	return result, nil
}

func findApp(apps []manifest.LoadedApp, appName string) (manifest.LoadedApp, bool) {
	for _, app := range apps {
		if app.Manifest.Name == appName {
			return app, true
		}
	}
	return manifest.LoadedApp{}, false
}

func preflightDirectory(path string) error {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("stat %s: %w", path, err)
	}
	if !info.IsDir() {
		return fmt.Errorf("%s must be a directory", path)
	}
	return nil
}

func preflightRegularFile(path string) error {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("stat %s: %w", path, err)
	}
	if info.IsDir() || !info.Mode().IsRegular() {
		return fmt.Errorf("%s must be a regular file", path)
	}
	return nil
}

func jobFileStatus(path string, source []byte, options GenerateOptions) (string, error) {
	existing, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			if options.DryRun {
				return "would create", nil
			}
			return "created", nil
		}
		return "", fmt.Errorf("read job metadata %s: %w", path, err)
	}
	if bytes.Equal(existing, source) {
		return "unchanged", nil
	}
	if options.Force && bytes.Contains(existing, []byte(jobMetadataMarker)) {
		if options.DryRun {
			return "would update", nil
		}
		return "updated", nil
	}
	if _, err := jobs.LoadFile(path); err != nil {
		return "", err
	}
	return "existing", nil
}

func runFileStatus(path string, dryRun bool) (string, error) {
	exists, hasRun, err := runnergen.InspectFunctionFile(path, "Run")
	if err != nil {
		return "", err
	}
	if !exists {
		if dryRun {
			return "would create", nil
		}
		return "created", nil
	}
	if !hasRun {
		return "", fmt.Errorf("%s exists but does not expose Run(ctx context.Context, job dygo.JobExecution) error", path)
	}
	return "existing", nil
}

func renderJobMetadata(jobName string) []byte {
	return []byte(fmt.Sprintf(`# %s. Edit as needed.
label: %s
queue: default
timeout: 30s
retry:
  attempts: 3
`, jobMetadataMarker, labelForName(jobName)))
}

func renderRunSource(appName string, jobName string) ([]byte, error) {
	source := fmt.Sprintf(`package job

import (
	"context"

	"github.com/hapyco/dygo/pkg/dygo"
)

func Run(ctx context.Context, job dygo.JobExecution) error {
	// TODO(%s/%s): implement job behavior.
	return nil
}
`, appName, jobName)
	return runnergen.FormatGoSource([]byte(source))
}

func labelForName(name string) string {
	parts := strings.Split(name, "-")
	for index, part := range parts {
		if part == "" {
			continue
		}
		parts[index] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, " ")
}

func writeStatus(written bool) string {
	if written {
		return "updated"
	}
	return "unchanged"
}
