// Package generate writes dygo app and Entity scaffolds.
package generate

import (
	"bytes"
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/hapyco/dygo/internal/reserved"
	"github.com/hapyco/dygo/internal/shape"
)

const GeneratedMarker = "Code generated by dygo generate"

//go:embed templates/*
var templateFS embed.FS

// Options controls scaffold writes.
type Options struct {
	Root     string
	DryRun   bool
	Force    bool
	NoAccess bool
}

// Plan describes scaffold file actions.
type Plan struct {
	Actions []Action
}

// Action describes one generated file action.
type Action struct {
	Path   string
	Status string
}

type fileSpec struct {
	Path     string
	Mode     os.FileMode
	Template string
	Data     templateData
}

type templateData struct {
	App        string
	Name       string
	Label      string
	Entity     string
	EntityVar  string
	Collection string
}

// App generates a project-owned app skeleton.
func App(options Options, appName string) (Plan, error) {
	if err := shape.ValidateMetadataName("app", appName); err != nil {
		return Plan{}, err
	}
	if reserved.IsApp(appName) {
		return Plan{}, fmt.Errorf("app name %q is reserved for framework-managed apps", appName)
	}
	data := templateData{App: appName, Name: appName, Label: labelForName(appName)}
	files := []fileSpec{
		{Path: shape.AppManifestPath(appName), Mode: 0o644, Template: "app.yml.tmpl", Data: data},
	}
	if !options.NoAccess {
		files = append(files, fileSpec{Path: shape.AppRolesPath(appName), Mode: 0o644, Template: "roles.yml.tmpl", Data: data})
	}
	files = append(files, fileSpec{Path: shape.AppSchedulesPath(appName), Mode: 0o644, Template: "schedules.yml.tmpl", Data: data})
	return writeScaffold(options, []string{
		shape.AppEntitiesPath(appName),
		shape.AppCollectionDirPath(appName),
		shape.AppJobsPath(appName),
		shape.AppPagesPath(appName),
		shape.AppReportsPath(appName),
	}, files)
}

// Entity generates the metadata and optional companion files for one Entity.
func Entity(options Options, ref shape.AppRef, includeFixture bool, includeTest bool) (Plan, error) {
	data := templateData{
		App:       ref.App,
		Name:      ref.Name,
		Label:     labelForName(ref.Name),
		Entity:    ref.Name,
		EntityVar: identifierForName(ref.Name),
	}
	entityDir := filepath.ToSlash(filepath.Join(shape.AppDir(ref.App), shape.EntityDir(ref.Name)))
	files := []fileSpec{
		{Path: filepath.ToSlash(filepath.Join(shape.AppDir(ref.App), shape.EntityMetadataPath(ref.Name))), Mode: 0o644, Template: "entity.yml.tmpl", Data: data},
	}
	if !options.NoAccess {
		files = append(files, accessSpec(ref))
	}
	if includeFixture {
		files = append(files, fixtureSpec(ref))
	}
	if includeTest {
		files = append(files, testSpec(ref))
	}
	return writeScaffold(options, []string{entityDir}, files)
}

// Collection generates reusable collection row metadata.
func Collection(options Options, ref shape.AppRef) (Plan, error) {
	data := templateData{App: ref.App, Name: ref.Name, Label: labelForName(ref.Name), Collection: ref.Name}
	return writeScaffold(options, []string{
		shape.AppCollectionDirPath(ref.App),
	}, []fileSpec{
		{Path: filepath.ToSlash(filepath.Join(shape.AppDir(ref.App), shape.CollectionMetadataPath(ref.Name))), Mode: 0o644, Template: "collection.yml.tmpl", Data: data},
	})
}

// Fixture generates a fixture skeleton for an existing Entity bundle.
func Fixture(options Options, ref shape.AppRef) (Plan, error) {
	return writeScaffold(options, nil, []fileSpec{fixtureSpec(ref)})
}

// Test generates Go test boilerplate for an Entity bundle.
func Test(options Options, ref shape.AppRef) (Plan, error) {
	return writeScaffold(options, nil, []fileSpec{testSpec(ref)})
}

func fixtureSpec(ref shape.AppRef) fileSpec {
	return fileSpec{
		Path: filepath.ToSlash(filepath.Join(shape.AppDir(ref.App), shape.EntityFixturesPath(ref.Name))),
		Mode: 0o644, Template: "fixtures.yml.tmpl",
		Data: templateData{App: ref.App, Name: ref.Name, Label: labelForName(ref.Name), Entity: ref.Name},
	}
}

func accessSpec(ref shape.AppRef) fileSpec {
	return fileSpec{
		Path: shape.AppEntityAccessPath(ref.App, ref.Name),
		Mode: 0o644, Template: "access.yml.tmpl",
		Data: templateData{App: ref.App, Name: ref.Name, Label: labelForName(ref.Name), Entity: ref.Name},
	}
}

func testSpec(ref shape.AppRef) fileSpec {
	return fileSpec{
		Path: filepath.ToSlash(filepath.Join(shape.AppDir(ref.App), shape.EntityDir(ref.Name), "hooks_test.go")),
		Mode: 0o644, Template: "hooks_test.go.tmpl",
		Data: templateData{App: ref.App, Name: ref.Name, Label: labelForName(ref.Name), Entity: ref.Name, EntityVar: identifierForName(ref.Name)},
	}
}

func writeScaffold(options Options, dirs []string, files []fileSpec) (Plan, error) {
	root := filepath.Clean(options.Root)
	if root == "." || strings.TrimSpace(root) == "" {
		return Plan{}, fmt.Errorf("project root is required")
	}
	var plan Plan
	for _, spec := range files {
		source, err := renderTemplate(spec.Template, spec.Data)
		if err != nil {
			return Plan{}, err
		}
		status, err := planFile(root, spec.Path, source, options)
		if err != nil {
			return Plan{}, err
		}
		plan.Actions = append(plan.Actions, Action{Path: spec.Path, Status: status})
	}
	if options.DryRun {
		return plan, nil
	}
	for _, dir := range dirs {
		if err := os.MkdirAll(filepath.Join(root, filepath.FromSlash(dir)), 0o755); err != nil {
			return Plan{}, fmt.Errorf("create directory %s: %w", dir, err)
		}
	}
	for _, spec := range files {
		source, err := renderTemplate(spec.Template, spec.Data)
		if err != nil {
			return Plan{}, err
		}
		if err := writeFile(root, spec, source, options); err != nil {
			return Plan{}, err
		}
	}
	return plan, nil
}

func planFile(root string, path string, source []byte, options Options) (string, error) {
	target := filepath.Join(root, filepath.FromSlash(path))
	existing, err := os.ReadFile(target)
	if err != nil {
		if os.IsNotExist(err) {
			if options.DryRun {
				return "would create", nil
			}
			return "created", nil
		}
		return "", fmt.Errorf("read %s: %w", path, err)
	}
	if bytes.Equal(existing, source) {
		return "unchanged", nil
	}
	if !isGenerated(existing) {
		return "", fmt.Errorf("%s exists and is not dygo-generated", path)
	}
	if !options.Force {
		return "", fmt.Errorf("%s already exists with dygo-generated content; rerun with --force to overwrite", path)
	}
	if options.DryRun {
		return "would update", nil
	}
	return "updated", nil
}

func writeFile(root string, spec fileSpec, source []byte, options Options) error {
	status, err := planFile(root, spec.Path, source, options)
	if err != nil {
		return err
	}
	if status == "unchanged" {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(filepath.Join(root, filepath.FromSlash(spec.Path))), 0o755); err != nil {
		return fmt.Errorf("create directory for %s: %w", spec.Path, err)
	}
	if err := os.WriteFile(filepath.Join(root, filepath.FromSlash(spec.Path)), source, spec.Mode); err != nil {
		return fmt.Errorf("write %s: %w", spec.Path, err)
	}
	return nil
}

func renderTemplate(name string, data templateData) ([]byte, error) {
	tmpl, err := template.ParseFS(templateFS, "templates/"+name)
	if err != nil {
		return nil, fmt.Errorf("parse scaffold template %s: %w", name, err)
	}
	var out bytes.Buffer
	if err := tmpl.Execute(&out, data); err != nil {
		return nil, fmt.Errorf("render scaffold template %s: %w", name, err)
	}
	return out.Bytes(), nil
}

func isGenerated(data []byte) bool {
	return strings.Contains(string(data), GeneratedMarker)
}

func labelForName(name string) string {
	parts := strings.Split(name, "-")
	for index, part := range parts {
		if part == "" {
			continue
		}
		parts[index] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, " ")
}

func identifierForName(name string) string {
	label := labelForName(name)
	return strings.ReplaceAll(label, " ", "")
}
