package upgrade

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestUpgradeProjectUpdatesGoModAndGeneratedRunner(t *testing.T) {
	root := newUpgradeTestProject(t)

	result, err := UpgradeProject(context.Background(), ProjectOptions{
		Root:          root,
		TargetVersion: "v1.2.3",
		Yes:           true,
		SkipTidy:      true,
	})
	if err != nil {
		t.Fatalf("UpgradeProject() error = %v, want nil", err)
	}
	if !result.Updated {
		t.Fatalf("UpgradeProject() result = %+v, want Updated", result)
	}
	goMod := readUpgradeTestFile(t, filepath.Join(root, "go.mod"))
	for _, want := range []string{
		"require github.com/dygo-dev/dygo v1.2.3",
	} {
		if !strings.Contains(goMod, want) {
			t.Fatalf("go.mod = %q, want substring %q", goMod, want)
		}
	}
	if strings.Contains(goMod, "replace github.com/dygo-dev/dygo") {
		t.Fatalf("go.mod = %q, want dygo replace removed", goMod)
	}
	runner := readUpgradeTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"))
	if !strings.Contains(runner, "Code generated by dygo hooks generate") {
		t.Fatalf("runner = %q, want regenerated dygo-managed runner", runner)
	}
}

func TestUpgradeProjectRefusesDirtyGitWorktree(t *testing.T) {
	root := newUpgradeTestProject(t)
	runUpgradeTestCommand(t, root, "git", "init")

	_, err := UpgradeProject(context.Background(), ProjectOptions{
		Root:          root,
		TargetVersion: "v1.2.3",
		Yes:           true,
		SkipTidy:      true,
	})
	if err == nil {
		t.Fatal("UpgradeProject() error = nil, want dirty worktree error")
	}
	if !strings.Contains(err.Error(), "worktree is dirty") {
		t.Fatalf("UpgradeProject() error = %q, want dirty worktree", err.Error())
	}
	goMod := readUpgradeTestFile(t, filepath.Join(root, "go.mod"))
	if strings.Contains(goMod, "v1.2.3") {
		t.Fatalf("go.mod = %q, want no writes after dirty worktree refusal", goMod)
	}
}

func TestUpgradeProjectRefusesCustomRunnerBeforeGoModWrite(t *testing.T) {
	root := newUpgradeTestProject(t)
	writeUpgradeTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"), "package main\n")

	_, err := UpgradeProject(context.Background(), ProjectOptions{
		Root:          root,
		TargetVersion: "v1.2.3",
		Yes:           true,
		SkipTidy:      true,
	})
	if err == nil {
		t.Fatal("UpgradeProject() error = nil, want custom runner error")
	}
	if !strings.Contains(err.Error(), "exists and is not dygo-generated") {
		t.Fatalf("UpgradeProject() error = %q, want custom runner error", err.Error())
	}
	goMod := readUpgradeTestFile(t, filepath.Join(root, "go.mod"))
	if strings.Contains(goMod, "v1.2.3") {
		t.Fatalf("go.mod = %q, want no writes after custom runner refusal", goMod)
	}
}

func newUpgradeTestProject(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	writeUpgradeTestFile(t, filepath.Join(root, "dygo.yml"), "name: acme\n")
	writeUpgradeTestFile(t, filepath.Join(root, "go.mod"), `module example.com/acme

go 1.26.2

require github.com/dygo-dev/dygo v0.0.0

replace github.com/dygo-dev/dygo => /tmp/dygo
`)
	writeUpgradeTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"), `// Code generated by dygo new; DO NOT EDIT.

package main

func main() {}
`)
	writeUpgradeTestFile(t, filepath.Join(root, "apps", "sales", "app.yml"), `name: sales
label: Sales
version: 0.1.0
`)
	return root
}

func writeUpgradeTestFile(t *testing.T, path string, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("MkdirAll(%s) error = %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("WriteFile(%s) error = %v", path, err)
	}
}

func readUpgradeTestFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(%s) error = %v", path, err)
	}
	return string(data)
}

func runUpgradeTestCommand(t *testing.T, dir string, name string, args ...string) {
	t.Helper()
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("%s %s error = %v\n%s", name, strings.Join(args, " "), err, string(output))
	}
}
