package upgrade

import (
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"testing/fstest"

	"github.com/hapyco/dygo/internal/runnergen"
)

func TestUpgradeProjectUpdatesGoModAndGeneratedRunner(t *testing.T) {
	root := newUpgradeTestProject(t)

	result, err := UpgradeProject(context.Background(), ProjectOptions{
		Root:          root,
		TargetVersion: "v1.2.3",
		Yes:           true,
		SkipTidy:      true,
		StudioAssets: fstest.MapFS{
			"index.html":      {Data: []byte("<html>studio v1.2.3</html>")},
			"assets/index.js": {Data: []byte("console.log('studio')")},
		},
	})
	if err != nil {
		t.Fatalf("UpgradeProject() error = %v, want nil", err)
	}
	if !result.Updated {
		t.Fatalf("UpgradeProject() result = %+v, want Updated", result)
	}
	goMod := readUpgradeTestFile(t, filepath.Join(root, "go.mod"))
	for _, want := range []string{
		"require github.com/hapyco/dygo v1.2.3",
	} {
		if !strings.Contains(goMod, want) {
			t.Fatalf("go.mod = %q, want substring %q", goMod, want)
		}
	}
	if strings.Contains(goMod, "replace github.com/hapyco/dygo") {
		t.Fatalf("go.mod = %q, want dygo replace removed", goMod)
	}
	runner := readUpgradeTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"))
	if !strings.Contains(runner, "Code generated by dygo generate") {
		t.Fatalf("runner = %q, want regenerated dygo-managed runner", runner)
	}
	if result.StudioSource != "configured Studio assets" {
		t.Fatalf("UpgradeProject() result = %+v, want Studio cache update", result)
	}
	if !result.CoreUpdated || result.CoreSource != "bundled Core App" {
		t.Fatalf("UpgradeProject() result = %+v, want bundled Core App update", result)
	}
	if !result.MetadataMigrationRequired {
		t.Fatalf("UpgradeProject() result = %+v, want metadata migration step", result)
	}
	gitignore := readUpgradeTestFile(t, filepath.Join(root, ".gitignore"))
	for _, want := range []string{"!.dygo/apps/studio/**", ".dygo/apps/studio/ui/**"} {
		if !strings.Contains(gitignore, want) {
			t.Fatalf(".gitignore = %q, want Studio tracking rule %q", gitignore, want)
		}
	}
	if _, err := os.Stat(filepath.Join(root, ".dygo", "apps", "core", "app.yml")); err != nil {
		t.Fatalf("Stat(upgraded Core App) error = %v", err)
	}
	studioIndex := readUpgradeTestFile(t, filepath.Join(root, ".dygo", "apps", "studio", "ui", "dist", "index.html"))
	if !strings.Contains(studioIndex, "studio v1.2.3") {
		t.Fatalf("Studio index = %q, want upgraded Studio cache", studioIndex)
	}
	studioManifest := readUpgradeTestFile(t, filepath.Join(root, ".dygo", "apps", "studio", "app.yml"))
	if !strings.Contains(studioManifest, "name: studio") {
		t.Fatalf("Studio manifest = %q, want upgraded Studio App metadata", studioManifest)
	}
	studioHome := readUpgradeTestFile(t, filepath.Join(root, ".dygo", "apps", "studio", "pages", "home", "home.page.yml"))
	if !strings.Contains(studioHome, "renderer: entity-index") {
		t.Fatalf("Studio home Page = %q, want bundled entity-index renderer", studioHome)
	}
}

func TestUpgradeProjectNoOpsWhenVersionMatchesTarget(t *testing.T) {
	root := newUpgradeTestProject(t)
	writeUpgradeTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"), "package main\n")
	calledRunner := false
	calledConfirm := false

	result, err := UpgradeProject(context.Background(), ProjectOptions{
		Root:          root,
		TargetVersion: "v0.0.0",
		CommandRunner: func(context.Context, string, string, ...string) ([]byte, error) {
			calledRunner = true
			return nil, nil
		},
		Confirm: func(context.Context, string) (bool, error) {
			calledConfirm = true
			return true, nil
		},
		StudioAssets: fstest.MapFS{
			"index.html": {Data: []byte("<html>studio</html>")},
		},
	})
	if err != nil {
		t.Fatalf("UpgradeProject() error = %v, want nil", err)
	}
	if result.WouldUpdate || result.Updated || result.RunnerUpdated {
		t.Fatalf("UpgradeProject() result = %+v, want no-op", result)
	}
	if result.CurrentVersion != "v0.0.0" || result.TargetVersion != "v0.0.0" {
		t.Fatalf("UpgradeProject() result = %+v, want matching versions", result)
	}
	if calledRunner || calledConfirm {
		t.Fatalf("UpgradeProject() called runner=%v confirm=%v, want neither", calledRunner, calledConfirm)
	}
	if _, err := os.Stat(filepath.Join(root, ".dygo", "apps", "studio", "ui", "dist", "index.html")); !os.IsNotExist(err) {
		t.Fatalf("Studio cache stat error = %v, want missing cache after no-op", err)
	}
}

func TestUpgradeProjectRefusesDirtyGitWorktree(t *testing.T) {
	root := newUpgradeTestProject(t)
	runUpgradeTestCommand(t, root, "git", "init")

	_, err := UpgradeProject(context.Background(), ProjectOptions{
		Root:          root,
		TargetVersion: "v1.2.3",
		Yes:           true,
		SkipTidy:      true,
	})
	if err == nil {
		t.Fatal("UpgradeProject() error = nil, want dirty worktree error")
	}
	if !strings.Contains(err.Error(), "worktree is dirty") {
		t.Fatalf("UpgradeProject() error = %q, want dirty worktree", err.Error())
	}
	goMod := readUpgradeTestFile(t, filepath.Join(root, "go.mod"))
	if strings.Contains(goMod, "v1.2.3") {
		t.Fatalf("go.mod = %q, want no writes after dirty worktree refusal", goMod)
	}
}

func TestUpgradeProjectRefusesCustomRunnerBeforeGoModWrite(t *testing.T) {
	root := newUpgradeTestProject(t)
	writeUpgradeTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"), "package main\n")

	_, err := UpgradeProject(context.Background(), ProjectOptions{
		Root:          root,
		TargetVersion: "v1.2.3",
		Yes:           true,
		SkipTidy:      true,
	})
	if err == nil {
		t.Fatal("UpgradeProject() error = nil, want custom runner error")
	}
	if !strings.Contains(err.Error(), "exists and is not dygo-generated") {
		t.Fatalf("UpgradeProject() error = %q, want custom runner error", err.Error())
	}
	goMod := readUpgradeTestFile(t, filepath.Join(root, "go.mod"))
	if strings.Contains(goMod, "v1.2.3") {
		t.Fatalf("go.mod = %q, want no writes after custom runner refusal", goMod)
	}
}

func TestUpgradeProjectRestoresGoModWhenTidyFails(t *testing.T) {
	root := newUpgradeTestProject(t)
	goModPath := filepath.Join(root, "go.mod")
	original := readUpgradeTestFile(t, goModPath)
	commandRunner := func(_ context.Context, dir string, name string, args ...string) ([]byte, error) {
		switch {
		case name == "git" && len(args) > 0 && args[0] == "rev-parse":
			return nil, nil
		case name == "git" && len(args) > 0 && args[0] == "status":
			return nil, nil
		case name == "go" && len(args) > 1 && args[0] == "mod" && args[1] == "tidy":
			if err := os.WriteFile(filepath.Join(root, "go.sum"), []byte("temporary checksum\n"), 0o644); err != nil {
				return nil, err
			}
			return nil, errors.New("tidy failed")
		case name == "go" && len(args) > 1 && args[0] == "mod" && args[1] == "edit":
			if err := os.WriteFile(goModPath, []byte("module example.com/acme\n\nrequire github.com/hapyco/dygo v1.2.3\n"), 0o644); err != nil {
				return nil, err
			}
			return nil, nil
		default:
			return nil, nil
		}
	}

	_, err := UpgradeProject(context.Background(), ProjectOptions{
		Root:          root,
		TargetVersion: "v1.2.3",
		Yes:           true,
		CommandRunner: commandRunner,
		StudioAssets: fstest.MapFS{
			"index.html": {Data: []byte("<html>studio</html>")},
		},
	})
	if err == nil {
		t.Fatal("UpgradeProject() error = nil, want tidy failure")
	}
	if got := readUpgradeTestFile(t, goModPath); got != original {
		t.Fatalf("go.mod after failed upgrade = %q, want original %q", got, original)
	}
	if _, err := os.Stat(filepath.Join(root, "go.sum")); !os.IsNotExist(err) {
		t.Fatalf("go.sum stat error = %v, want absent after failed upgrade", err)
	}
}

func TestRunCanRetryAfterTidyFailure(t *testing.T) {
	root := newUpgradeTestProject(t)
	runUpgradeTestCommand(t, root, "git", "init")
	runUpgradeTestCommand(t, root, "git", "config", "user.email", "test@example.com")
	runUpgradeTestCommand(t, root, "git", "config", "user.name", "Dygo Test")
	runUpgradeTestCommand(t, root, "git", "add", ".")
	runUpgradeTestCommand(t, root, "git", "commit", "-m", "initial")

	tidyAttempts := 0
	commandRunner := func(ctx context.Context, dir string, name string, args ...string) ([]byte, error) {
		if name == "git" {
			return defaultCommandRunner(ctx, dir, name, args...)
		}
		if name == "go" && len(args) > 1 && args[0] == "mod" && args[1] == "edit" {
			if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte("module example.com/acme\n\nrequire github.com/hapyco/dygo v1.0.0\n"), 0o644); err != nil {
				return nil, err
			}
			return nil, nil
		}
		if name == "go" && len(args) > 1 && args[0] == "mod" && args[1] == "tidy" {
			tidyAttempts++
			if tidyAttempts == 1 {
				return nil, errors.New("tidy failed")
			}
		}
		return nil, nil
	}
	options := Options{CurrentVersion: "v1.0.0", TargetVersion: "v1.0.0", WorkingDir: root, Yes: true, CommandRunner: commandRunner}
	if _, err := Run(context.Background(), options); err == nil {
		t.Fatal("Run(first upgrade) error = nil, want tidy failure")
	}
	result, err := Run(context.Background(), options)
	if err != nil {
		t.Fatalf("Run(retry) error = %v, want nil", err)
	}
	if result.Project == nil || !result.Project.Updated {
		t.Fatalf("Run(retry) result = %+v, want completed upgrade", result)
	}
	if got, err := ReadProjectVersion(root); err != nil || got != "v1.0.0" {
		t.Fatalf("ReadProjectVersion(retry) = %q, %v, want v1.0.0", got, err)
	}
}

func TestRunRestoresManagedFilesWhenRunnerFailsAfterAssets(t *testing.T) {
	root := newUpgradeTestProject(t)
	writeUpgradeTestFile(t, filepath.Join(root, ".dygo", "apps", "core", "app.yml"), "name: core\nlabel: Core\nversion: 0.1.0\n")
	runUpgradeTestCommand(t, root, "git", "init")
	runUpgradeTestCommand(t, root, "git", "config", "user.email", "test@example.com")
	runUpgradeTestCommand(t, root, "git", "config", "user.name", "Dygo Test")
	runUpgradeTestCommand(t, root, "git", "add", ".")
	runUpgradeTestCommand(t, root, "git", "commit", "-m", "initial")

	originalRunner := readUpgradeTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"))
	runnerAttempts := 0
	previousRunner := updateProjectRunner
	updateProjectRunner = func(path string) (runnergen.RunnerUpdate, bool, error) {
		runnerAttempts++
		if runnerAttempts == 1 {
			if _, err := os.Stat(filepath.Join(root, ".dygo", "apps", "studio", "app.yml")); err != nil {
				t.Errorf("runner update ran before Studio install: %v", err)
			}
			if _, err := os.Stat(filepath.Join(root, ".dygo", "apps", "core", "app.yml")); err != nil {
				t.Errorf("runner update ran before Core install: %v", err)
			}
			return runnergen.RunnerUpdate{}, false, errors.New("runner write failed")
		}
		return previousRunner(path)
	}
	defer func() { updateProjectRunner = previousRunner }()

	commandRunner := func(ctx context.Context, dir string, name string, args ...string) ([]byte, error) {
		if name == "git" {
			return defaultCommandRunner(ctx, dir, name, args...)
		}
		if name == "go" && len(args) > 1 && args[0] == "mod" && args[1] == "edit" {
			if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte("module example.com/acme\n\nrequire github.com/hapyco/dygo v1.0.0\n"), 0o644); err != nil {
				return nil, err
			}
		}
		return nil, nil
	}
	options := Options{CurrentVersion: "v1.0.0", TargetVersion: "v1.0.0", WorkingDir: root, Yes: true, CommandRunner: commandRunner}
	if _, err := Run(context.Background(), options); err == nil {
		t.Fatal("Run(first upgrade) error = nil, want runner failure")
	}
	if got := readUpgradeTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go")); got != originalRunner {
		t.Fatalf("runner after failed upgrade = %q, want original %q", got, originalRunner)
	}
	if got := readUpgradeTestFile(t, filepath.Join(root, ".dygo", "apps", "core", "app.yml")); !strings.Contains(got, "version: 0.1.0") {
		t.Fatalf("Core after failed upgrade = %q, want original metadata", got)
	}
	if _, err := os.Stat(filepath.Join(root, ".dygo", "apps", "studio")); !os.IsNotExist(err) {
		t.Fatalf("Studio after failed upgrade stat error = %v, want absent", err)
	}
	result, err := Run(context.Background(), options)
	if err != nil {
		t.Fatalf("Run(retry) error = %v, want nil", err)
	}
	if result.Project == nil || !result.Project.Updated {
		t.Fatalf("Run(retry) result = %+v, want completed upgrade", result)
	}
}

func newUpgradeTestProject(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	writeUpgradeTestFile(t, filepath.Join(root, "dygo.yml"), "name: acme\n")
	writeUpgradeTestFile(t, filepath.Join(root, "go.mod"), `module example.com/acme

go 1.26.2

require github.com/hapyco/dygo v0.0.0

replace github.com/hapyco/dygo => /tmp/dygo
`)
	writeUpgradeTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"), `// Code generated by dygo new; DO NOT EDIT.

package main

func main() {}
`)
	writeUpgradeTestFile(t, filepath.Join(root, "apps", "sales", "app.yml"), `name: sales
label: Sales
version: 0.1.0
`)
	return root
}

func writeUpgradeTestFile(t *testing.T, path string, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("MkdirAll(%s) error = %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("WriteFile(%s) error = %v", path, err)
	}
}

func readUpgradeTestFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(%s) error = %v", path, err)
	}
	return string(data)
}

func runUpgradeTestCommand(t *testing.T, dir string, name string, args ...string) {
	t.Helper()
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("%s %s error = %v\n%s", name, strings.Join(args, " "), err, string(output))
	}
}
